#注意：使用前请确认你已经在issue里搜索过，确保不存在和你类似的问题。
#
#1. 使用求助？
#
#本地-命令行
#本地-python代码
#
#本地版本：
#
#
#你想要干什么？
#
#
# 你做了啥？有代码请贴代码
#
#
# 遇到什么困难？截图程序输出

name: Ask For Help
description: 使用求助
labels: [ "help wanted" ]

body:
  - type: checkboxes
    attributes:
      label: 注意事项
      options:
        - label: 提ISSUE请确认你已经在issue里搜索过，确保不存在和你类似的问题。
          required: true

  - type: dropdown
    attributes:
      label: 使用方式
      description: 你的使用方式？
      multiple: false
      options:
        - GitHub Actions
        - Python代码
        - jmcomic命令行
      default: 1
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        简单描述一下你的目的

  - type: markdown
    attributes:
      value: |
        简单描述一下你的做法

  - type: markdown
    attributes:
      value: |
        简单描述一下你遇到的困难或者问题
