name: Bug
title: '[Bug] '
description: 使用求助
labels: [ 'bug' ]

body:
  - type: checkboxes
    attributes:
      label: 注意事项
      options:
        - label: 提ISSUE前，请确认你已经在issue里搜索过类似的问题，也许你的问题已经被解决过了
          required: true
        - label: 是否是最新版本的jmcomic（GitHub Actions不用填）

  - type: dropdown
    attributes:
      label: 你使用的是哪种方式？
      multiple: false
      options:
        - Python代码
        - GitHub Actions
        - jmcomic命令行
    validations:
      required: true

  - type: textarea
    attributes:
      label: 你的目的？
      placeholder: 简单描述一下你想要干什么

  - type: textarea
    attributes:
      label: 你的预期
      placeholder: 描述一下你的预期是什么

  - type: textarea
    attributes:
      label: 实际结果
      placeholder: 描述一下实际结果是什么

