name: Auto Release


on:
  workflow_dispatch:

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Extract Version and Details
        id: extract
        run: |
          commit_message=$(git log --format=%B -n 1 ${{ github.sha }})
          pip install commonX
          python setoutput.py "$commit_message"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: true
          tag_name: ${{ steps.extract.outputs.tag }}
          body_path: release_body.txt
