name: Auto Release

on:
  push:
    branches:
      - master

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Extract Version and Details
        id: extract
        run: |
          commit_message=$(git log --format=%B -n 1 ${{ github.sha }})
          version=$(echo $commit_message | grep -oP '(?<=publish\s):\S+')
          details=$(echo $commit_message | grep -oP '(?<=:\s).*')
          echo "::set-output name=version::$version"
          echo "::set-output name=details::$details"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract.outputs.version }}
          release_name: ${{ steps.extract.outputs.version }}
          body: ${{ steps.extract.outputs.details }}
