name: contributions

on:
  workflow_dispatch:
  push: 

jobs:
  create-release:
    name: Create
    runs-on: ubuntu-latest

    steps:
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v3.0.0
